### ISSUE TITLE
Internalization

### ISSUE THREAD

**Issue by aAXEe** [aAXEe/online_chart_ol3#3]
# Motivation

Our map is used worldwide. Excerpt from the statistics from the [current map](http://map.openseamap.org):

![ausschnitt statistik oseam map](https://cloud.githubusercontent.com/assets/3298652/13229134/a50c5d72-d99f-11e5-9113-59802974e16d.png)
# State

[React-intl](http://formatjs.io/react/) is in place at https://github.com/aAXEe/online_chart_ol3/blob/master/src/javascripts/app.js.
# Todo
- [x] re-factor translation messages out of app.js
- [x] add language detection
- [x] add user interface to change the language
- [ ] allow external translators to translate the strings
  Proposal: https://translatewiki.net/
- [x] remove all hard-coded strings
  Change eslint warning `react/jsx-no-literals` to error level

**Comment by Nautic** [comment]
Internationalisierung ist wichtig, damit die Karte benutzt werden kann 
und Benutzer die Daten verbessern können:
- Karte und Apps (de, en)
- Website (de, en, plus Sprachen für die es nachhaltig Übersetzer gibt)
- Wiki (de, en)
- Tutorials (de, en)

Am Wichtigsten ist eine **multilinguale Karte**

Alle Orte, Häfen und Marinas 
**lokaler Name** plus **endonymer internationaler Name**

umschaltbar in die wichtigsten **Schriftsysteme**:
    Lateinisch + international
    Kyrillisch + international
    Arabisch + international
    Chinesisch + international

**Comment by mojoaxel** [comment]
removed all hard coded string with d16c32f69f755f3e5d8bdfd561c6b8ec2eaca9ff

**Comment by aAXEe** [comment]
84c0177b0b1f5bc906bd9029428465a697996d45 did all the refactoring.
Translations live now in https://github.com/aAXEe/online_chart_ol3/tree/master/intl
